{
 "title": "Demo",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  { "title": "Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Targets Health",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "up", "legendFormat": "{{ job }}" }
   ]
  },
  { "title": "Go App", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "App API Request Total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "go_app_api_request_counter", "legendFormat": "{{ instance }}" }
   ]
  },
  { "title": "Host", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "CPU Usage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg by(instance) (irate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100)"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "job:node_memory_MemAvailable_bytes:available",
     "legendFormat": "{{ job }}"
    }
   ]
  },
  {
   "title": "Up Time",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{job=\"node_exporter\"}"
    }
   ]
  },
  {
   "title": "CPU Usage by Modes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by(instance) (irate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "idle"
    },
    {
     "expr": "100 - (avg by(instance) (irate(node_cpu_seconds_total{mode=\"user\"}[1m])) * 100)",
     "legendFormat": "user"
    },
    {
     "expr": "100 - (avg by(instance) (irate(node_cpu_seconds_total{mode=\"system\"}[1m])) * 100)",
     "legendFormat": "system"
    },
    {
     "expr": "100 - (avg by(instance) (irate(node_cpu_seconds_total{mode=\"iowait\"}[1m])) * 100)",
     "legendFormat": "iowait"
    }
   ]
  },
  {
   "title": "File System Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum by(instance) (node_filesystem_free_bytes) / sum by(instance) (node_filesystem_size_bytes)) * 100"
    }
   ]
  }
 ]
}